version: '3'
services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: fg_web
    volumes:
      - ./container:/home/web
    tty: true
    ports:
      - "3001:3001"
